package edu.escuelaing.database;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;

/**
 * Class that is responsible for making the connection to a Firebase database
 */
public class DataBaseConnector {


    private final String firebaseURL = "https://arep-lab3aguilera-default-rtdb.firebaseio.com/";
    private static DataBaseConnector _theInstance = new DataBaseConnector();


    /**
     * Class's default private constructor
     */
    private DataBaseConnector(){
    }

    /**
     * return an instance of the class
     * @return the instance of the clase
     */
    public static DataBaseConnector getInstance(){
        return _theInstance;
    }


    /**
     * Connects to a remote Firebase database and gets a random phrase
     * @param number the number that represents a random phrase generated
     * @return a random phrase generated by the database
     * @throws Exception If there is an error in connection with the database
     */
    public String getRandomSentence(int number) throws Exception {
        String sentence;
        try {
            String urlString = firebaseURL + "frase"+number+".json";
            URL url = new URL(firebaseURL + "frase"+number+".json");
            BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(url.openStream()));
            sentence = bufferedReader.readLine();
        } catch (IOException e) {
            throw new Exception("Connection error");
        }
        return sentence;
    }
}
